name: release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: { }

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Bump version (minor)
        id: bump
        run: |
          NEW_VER=$(npm version minor -m "chore(release): v%s" | sed 's/^v//')
          echo "new_ver=$NEW_VER" >> $GITHUB_OUTPUT

      - name: Update README with current version/date
        run: |
          DATE_ISO=$(date -u +"%Y-%m-%d")
          VER="${{ steps.bump.outputs.new_ver }}"
          perl -0777 -pe "s/<!--LAST_RELEASE-->.*?<!--\/LAST_RELEASE-->/<!--LAST_RELEASE-->v$VER on $DATE_ISO<!--\/LAST_RELEASE-->/s" -i README.md
          git add README.md
          git commit --amend --no-edit

      - name: Move tag to amended commit
        run: |
          VER="${{ steps.bump.outputs.new_ver }}"
          git tag -f "v$VER"

      - name: Push branch and tag
        run: |
          git push origin HEAD:main
          VER="${{ steps.bump.outputs.new_ver }}"
          git push -f origin "v$VER"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.new_ver }}
          name: v${{ steps.bump.outputs.new_ver }}
          draft: false
          prerelease: false
          files: |
            dist/autoconsent.playwright.js
